"use client";

import { useState, useEffect, useCallback } from "react";
import { KeyRound, RefreshCcw } from "lucide-react";
import { getImpersonationAuditLog } from "@/lib/impersonationService";

// Standalone file, same reason as UsersRolesTab.js: Next.js's dev compiler
// hangs on a page.js-to-page.js import. Read-only audit trail for the
// admin "Access Code" feature — see mobile-app/SUPABASE_IMPERSONATION.sql.
// The whole Settings page already blocks normal_admin before this ever
// renders, so no extra role gate is needed here.

const EVENT_LABELS = {
  created:        { label: "Code Generated", color: "bg-blue-100 text-blue-700" },
  redeemed:       { label: "Redeemed",       color: "bg-green-100 text-green-700" },
  redeem_failed:  { label: "Failed Attempt", color: "bg-red-100 text-red-600" },
};

const DETAIL_LABELS = {
  not_found:      "Invalid code",
  already_used:   "Code already used",
  expired:        "Code expired",
  role_mismatch:  "Wrong app (student/teacher mismatch)",
  target_deleted: "Account no longer exists",
};

function fmtWhen(iso) {
  if (!iso) return "—";
  return new Date(iso).toLocaleString("en-IN", {
    day: "2-digit", month: "short", year: "numeric",
    hour: "2-digit", minute: "2-digit",
  });
}

export default function ImpersonationLogTab() {
  const [rows, setRows]     = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError]   = useState("");

  const load = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const data = await getImpersonationAuditLog(200);
      setRows(data || []);
    } catch (err) {
      setError(err?.message || "Failed to load audit log.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
      <div className="px-5 py-4 border-b border-gray-100 flex items-center justify-between">
        <div>
          <h3 className="text-sm font-bold text-gray-700 flex items-center gap-2">
            <KeyRound className="w-4 h-4 text-gray-400" /> Admin Access Codes
          </h3>
          <p className="text-xs text-gray-400 mt-0.5">
            Every access code generated, redeemed, or failed — for student &amp; teacher account access without a password
          </p>
        </div>
        <button onClick={load} disabled={loading}
          className="flex items-center gap-2 px-3 py-2 rounded-xl text-xs font-semibold border border-gray-200 text-gray-600 hover:bg-gray-50 transition-colors disabled:opacity-40">
          <RefreshCcw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} /> Refresh
        </button>
      </div>

      {error && <div className="px-5 py-3 text-xs text-red-500 border-b border-gray-100">{error}</div>}

      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="bg-gray-50 border-b border-gray-100">
              <th className="px-5 py-3 text-left text-xs font-bold text-gray-500 uppercase tracking-wide">Event</th>
              <th className="px-4 py-3 text-left text-xs font-bold text-gray-500 uppercase tracking-wide">Target</th>
              <th className="px-4 py-3 text-left text-xs font-bold text-gray-500 uppercase tracking-wide">Generated By</th>
              <th className="px-4 py-3 text-left text-xs font-bold text-gray-500 uppercase tracking-wide">Detail</th>
              <th className="px-4 py-3 text-left text-xs font-bold text-gray-500 uppercase tracking-wide">When</th>
            </tr>
          </thead>
          <tbody>
            {loading && (
              <tr><td colSpan={5} className="px-5 py-8 text-center text-xs text-gray-400">Loading…</td></tr>
            )}
            {!loading && rows.length === 0 && (
              <tr><td colSpan={5} className="px-5 py-8 text-center text-xs text-gray-400">No access codes generated yet.</td></tr>
            )}
            {!loading && rows.map((r, i) => {
              const ev = EVENT_LABELS[r.event_type] || { label: r.event_type, color: "bg-gray-100 text-gray-600" };
              return (
                <tr key={r.id || i} className={`border-b border-gray-50 ${i % 2 === 0 ? "bg-white" : "bg-gray-50/30"}`}>
                  <td className="px-5 py-3">
                    <span className={`px-2.5 py-1 rounded-lg text-xs font-bold ${ev.color}`}>{ev.label}</span>
                  </td>
                  <td className="px-4 py-3 text-gray-700">
                    {r.target_label || <span className="text-gray-300">—</span>}
                    {r.target_type && <span className="text-gray-400 text-xs ml-1">({r.target_type})</span>}
                  </td>
                  <td className="px-4 py-3 text-gray-700">{r.created_by_name || <span className="text-gray-300">—</span>}</td>
                  <td className="px-4 py-3 text-gray-500 text-xs">{DETAIL_LABELS[r.detail] || r.detail || "—"}</td>
                  <td className="px-4 py-3 text-gray-500 text-xs whitespace-nowrap">{fmtWhen(r.occurred_at)}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}
